require 'json'
require 'pry'
require 'json-schema-generator'

file_name = 'qm.har'
file = File.read(file_name)
feature = file_name.split('.')
ename = feature[0]
har = JSON.parse(file)

# har['log']['entries'][0]['request']

@init_file = File.open("#{ename}.feature", "w")
@init_file.puts "#{ename}"
@init_file.puts "Feature: #{ename}"
@init_file.puts "\n Scenario: #{ename}"
@init_file.puts "  Description: This scenario generated by Rusteze"
@init_file.puts "  Given user login via sso using \"business\" credentials"
@init_file.puts "  And save response path \"$..data.access_token\" as \"ENV:EMAIL_BUSINESS\" at \"access_token\""

base_url = 'https://staging-backend-esign.mekari.io/core/api/v1/'

har['log']['entries'].each do |item|
  if item['request']['url'].include? base_url
    puts "=========================================="
    puts "*********************************" if item['request']['method'] == 'POST'
    puts "method : #{item['request']['method']}"
        
    puts "url : #{item['request']['url']}"
    puts "keys : #{item['request'].keys}"
    puts "body : #{item['request']['postData']['text']}" if item['request'].include? 'postData'
    puts "header : #{item['request']['header']}"
    puts "param : #{item['request']['queryString']}"

    puts "\nresponse:"

    puts "status : #{item['response']['status']}"
    puts "response body : #{item['response']['content']['text']}"

    path = item['request']['url'].sub(base_url, '')
    json_file = path.gsub('/','-')
    if item['request'].keys.include? 'postData'
      if !item['request']['postData']['text'].empty?
            
        @init_file.puts "  When user sends a #{item['request']['method']} request to \"#{path}\" with body:"
        @init_file.puts "  \"\"\""
        @init_file.puts "    #{item['request']['postData']['text']}"
        @init_file.puts "  \"\"\""
      else
        @init_file.puts "  When user sends a #{item['request']['method']} request to \"#{path}\""
      end
    else
      @init_file.puts "  When user sends a #{item['request']['method']} request to \"#{path}\""
    end

    @init_file.puts "  Then the response code should be \"#{item['response']['status']}\""
    if item['response']['content']['text'].nil?
    else
      @init_file.puts "  And the JSON response should follow schema \"#{json_file}.json\""
      json_string = JSON::SchemaGenerator.generate file, item['response']['content']['text'], {:schema_version => 'draft4'}
      File.open("#{json_file}.json", 'w') {|f| f.write(json_string) }
      File.open(Dir.pwd + "/#{json_file}.json", 'w') {|f| f.write(json_string) }
    end

  end
end

@init_file.close
