require 'json'
require 'pry'
require 'json-schema-generator'

file_name = 'invite_user.har'
file = File.read(file_name)
feature = file_name.split('.')
ename = feature[0]
har = JSON.parse(file)

# har['log']['entries'][0]['request']

@init_file = File.open("#{ename}.feature", "w")
@init_file.puts "#{ename}"
@init_file.puts "Feature: #{ename}"
@init_file.puts "\n Scenario: #{ename}"
@init_file.puts "  Description: This scenario generated by Rusteze"
@init_file.puts "  Given user login via sso using \"business\" credentials"
@init_file.puts "  And save response path \"$..data.access_token\" as \"ENV:EMAIL_BUSINESS\" at \"access_token\""

har['log']['entries'].each do |item|
  if item['request']['url'].include? 'https://sandbox-backend-esign.mekari.io/core/api/v1/'
    puts "=========================================="
    puts "*********************************" if item['request']['method'] == 'POST'
    puts "method : #{item['request']['method']}"
        
    puts "url : #{item['request']['url']}"
    puts "keys : #{item['request'].keys}"
    puts "body : #{item['request']['postData']['text']}" if item['request'].include? 'postData'
    puts "header : #{item['request']['header']}"
    puts "param : #{item['request']['queryString']}"

    puts "\nresponse:"

    puts "status : #{item['response']['status']}"
    puts "response body : #{item['response']['content']['text']}"


    if item['request'].keys.include? 'postData'
      if !item['request']['postData']['text'].empty?
            
        @init_file.puts "  When client sends a #{item['request']['method']} request to \"#{item['request']['url']}\" with body:"
        @init_file.puts "  \"\"\""
        @init_file.puts "    #{item['request']['postData']['text']}"
        @init_file.puts "  \"\"\""
      else
        @init_file.puts "  When client sends a #{item['request']['method']} request to \"#{item['request']['url']}\""
      end
    else
      @init_file.puts "  When client sends a #{item['request']['method']} request to \"#{item['request']['url']}\""
    end

    @init_file.puts "  Then response status should be \"#{item['response']['status']} \""
    if item['response']['content']['text'].nil?
    else
      @init_file.puts "  And response equal with schema \"#{ename}.json\""
      json_string = JSON::SchemaGenerator.generate file, item['response']['content']['text'], {:schema_version => 'draft4'}
      # File.open($json_schema + "/json_schema/#{ename}.json", 'w') {|f| f.write(json_string) }
      File.open(Dir.pwd + "/#{ename}.json", 'w') {|f| f.write(json_string) }
    end

  end
end

@init_file.close
